version: '3.10'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    stdin_open: true
    tty: true

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - DJANGO_SETTINGS_MODULE=app.settings
    depends_on:
      - db

  pygeoapi:
    build:
      context: ./pygeoapi
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./pygeoapi:/app
    depends_on:
      - db

  db:
    image: postgres:16
    container_name: postgres_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dolr
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
