# Generated by Django 5.1.4 on 2025-02-12 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_auth", "0002_userprofile_city_userprofile_district_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="village",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
