# Generated by Django 5.1.4 on 2025-02-01 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0002_otpverification_userprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='individual_type',
            new_name='login_as',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
