# Generated by Django 5.1.4 on 2025-02-16 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user_auth", "0003_userprofile_village"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userprofile",
            old_name="city",
            new_name="address",
        ),
        migrations.RenameField(
            model_name="userprofile",
            old_name="district",
            new_name="purpose_of_use",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="login_as",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="pin_code",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="state",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="user_type",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="village",
        ),
    ]
