# Generated by Django 5.1.4 on 2025-02-16 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("utils", "0003_plan_is_paid_reportplan_is_paid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reporttransaction",
            name="details",
        ),
        migrations.AddField(
            model_name="reporttransaction",
            name="district",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="reporttransaction",
            name="khata_no",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="reporttransaction",
            name="taluka",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="reporttransaction",
            name="village",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
