# Generated by Django 5.1.4 on 2025-01-18 07:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("utils", "0004_transaction_delete_transacton"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="duration",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
