# Generated by Django 5.1.4 on 2025-01-18 07:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("utils", "0005_transaction_duration"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transaction",
            name="duration",
        ),
        migrations.AddField(
            model_name="plan",
            name="duration",
            field=models.IntegerField(default=0),
        ),
    ]
