# Generated by Django 5.1.4 on 2025-02-09 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0002_fixedmvplans_fixedreportplans"),
    ]

    operations = [
        migrations.AddField(
            model_name="mvplanorder",
            name="fixed_plan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mv_orders",
                to="payments.fixedmvplans",
            ),
        ),
        migrations.AddField(
            model_name="reportplanorder",
            name="fixed_plan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="report_orders",
                to="payments.fixedreportplans",
            ),
        ),
    ]
