# Generated by Django 5.1.4 on 2025-02-16 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0003_mvplanorder_fixed_plan_reportplanorder_fixed_plan"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fixedreportplans",
            name="details",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
