# Generated by Django 5.1.4 on 2025-02-16 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0004_alter_fixedreportplans_details"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fixedmvplans",
            name="details",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
